my_site/common/urls.py
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView
from allauth.account.views import login, logout

app_name = "common"

urlpatterns = [
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
]

my_site/my_site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

app_name = "common"

urlpatterns = [
    path("admin/", admin.site.urls, name='admin'),
    path('', include('p_library.urls')),
    path('', include('common.urls')),
    path('accounts/', include('allauth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

my_site/p_library/urls.py
from django.urls import path

from p_library import views

app_name = "p_library"

urlpatterns = [
    path("", views.books_list, name="books"),
    path("books", views.books_list, name="books"),
    path("books/json", views.books_json),
    path("books/send", views.BookSend.as_view(), name="book_send"),
    path("books/create/", views.create_redirect, name="create"),
    path("books/create/full", views.create_book_full, name="create_full"),
    path("books/create/min", views.BookCreateMin.as_view(), name="create_min"),
    path("books/<int:pk>", views.BookDetail.as_view(), name="book_detail"),
    path("publishers", views.publisher_list, name="publishers"),
    path(
        "publishers/<int:pk>", views.PublisherDetail.as_view(), name="publisher_detail"
    ),
    path("friend/create", views.FriendAdd.as_view(), name="friend_create"),
    path("friends/<int:pk>", views.FriendDetail.as_view(), name="friend_detail"),
    path("friends", views.FriendList.as_view(), name="friend_list"),
    path("authors", views.AuthorList.as_view(), name="author_list"),
    path("authors/<int:pk>", views.AuthorDetail.as_view(), name="author_detail"),
]

my_site/templates/author_detail.html
{% extends "./base.html" %}

{% block content %}

<h4>{{ object.full_name }}</h4>

<div class="card" style="width: 18rem;">
    <ul class="list-group list-group-flush">
        <li class="list-group-item">Дата рождения: {{ object.birth_year }}</li>
        <li class="list-group-item">Страна: {{ object.country }}</li>
    </ul>
    <div class="card-body">
    <a href="" class="card-link">Книги</a>
  </div>
</div>


{% endblock %}

my_site/templates/authors.html
{% extends "./base.html" %}

{% block content %}

<h1>Авторы</h1>

<ul>
    {% for item in object_list %}
        <li><a href="{% url 'p_library:author_detail' item.pk %}">{{ item.full_name }}</a></li>
    {% endfor %}
</ul>


{% endblock %}

my_site/templates/base.html
{% load static %}
<!doctype html>
<html lang="ru">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width">
    <title>Билиотека</title>
    <meta name="description" content="Учебный пример">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
</head>

<body>
	<header>
		<div class="logo"> <img src="{% static 'logo/logo.png' %}" width=293 height=125 alt="logo">
		</div>
		<nav> 
			<ul class="nav">
				<li class="nav-item"><a href="{% url 'p_library:books' %}">Книги</a>
				<li class="nav-item"><a href="{% url 'p_library:create' %}">Добавить книгу</a>
				<li class="nav-item"><a href="{% url 'p_library:book_send' %}">Передать книгу</a>
				<li class="nav-item"><a href="{% url 'p_library:publishers' %}">Издательства</a>
				<li class="nav-item"><a href="{% url 'p_library:friend_list' %}">Друзья</a>
				<li class="nav-item"><a href="{% url 'p_library:friend_create' %}">Добавить друга</a>
				<li class="nav-item"><a href="{% url 'common:logout' %}">Выход</a>
			</ul>
		</nav>

	</header>
	
	<main>
		<div class="main_wrapper">
            {% block content %}
            {% endblock %}
		</div>
	</main>
	<aside>
		<div>
			<span>Aside</span>
		</div>
	</aside>
	<footer>
		<div class="address">
			<address>
				&copy; Skillfactory 2020  Contact: <a href="mailto:azat715@gmail.com">Mail me</a>
			</address>
		</div>
		
	</footer>
	{% block javascript %}
    {% endblock %}
</body>
</html>

my_site/templates/book_add.html
{% extends "./base.html" %}

{% block content %}

<form method="post" enctype="multipart/form-data">  
	{% csrf_token %}  
	{{ form.as_p }}  
	<input type="submit" class="btn btn-primary" value="Сохранить">  
</form>  

{% endblock %}

my_site/templates/book_add_full.html
{% extends "./base.html" %}

{% block content %}

{% load crispy_forms_tags %}

<form method="post" enctype="multipart/form-data"> 
	{% csrf_token %}
	<div class="container">
		<div class="row">
			<div class="col">
				<h4>Книга</h4>
					{{ book|crispy }}
    		</div>
			<div class="col">
				<h4>Автор</h4>
					<div class="author">
						 {% crispy author%} 
					</div>
				<h4>Издатель</h4>
					<div class="publisher">
						{{ publisher|crispy }}
					</div>
    		</div>
		</div>
		<div class="row">
			<div class="col">
			<a href="{% url 'p_library:create_min'%}">Свернуть</a>
			</div>
			<div class="col">
				<div class="d-flex flex-row justify-content-end">
					<input type="submit" class="btn btn-primary" value="Сохранить"/>
				</div>
				
			</div>
		</div>
	</div> 	
</form>  

{% endblock %}

{% block javascript %}
{% load static %}
{% comment %} <script src="{% static 'js/script.js' %}"></script> {% endcomment %}
{% endblock %}

my_site/templates/book_detail.html
{% extends "./base.html" %}

{% block content %}

<h4>Книга</h4>

<div class="card w-100" style="width: 18rem;">
    {% if object.cover %}
        <img src="{{ object.cover.url }}" class="card-img-top rounded mx-auto d-block" alt="Оболжка книги">
    {% else %}
        Нет изображения
    {% endif %}
    <div class="card-body">
        <h4 class="card-title">{{ object.title }}</h4>
        <p class="card-text">{{ object.description }}</p> 
    </div>
    <ul class="list-group list-group-flush">
        <li class="list-group-item">Автор: {{ author.full_name }}</li>
        <li class="list-group-item">Издатель: {{ publisher.name }}</li>
    </ul>
    <div class="card-body">
    <a href="" class="card-link">Автор</a>
    <a href="" class="card-link">Издатель</a>
  </div>
</div>

{% endblock %}

my_site/templates/book_send.html
{% extends "./base.html" %}

{% block content %}

<form method="post">  
	{% csrf_token %}  
	{{ form.as_p }}  
	<input type="submit" class="btn btn-primary" value="Передать">  
</form>  

{% endblock %}

my_site/templates/friend_detail.html
{% extends "./base.html" %}

{% block content %}

<h4>{{ object.name }}</h4>

<table class="table table-bordered">
    <tr>
        <td scope="col">Название книги</td>
        <td scope="col">Количество копий</td>
        <td scope="col">Дата</td>
    </tr>
    {% for item in sent_books %}
    <tr>
        <td >{{ item.book.title }}</td>
        <td>{{ item.copy_count_send }}</td>
        <td>{{ item.date_send }}</td>
        </td>
    </tr>
    {% endfor %}
</table>


{% endblock %}

my_site/templates/friends.html
{% extends "./base.html" %}

{% block content %}

<h1>Друзья</h1>

<ul>
    {% for item in object_list %}
        <li><a href="{% url 'p_library:friend_detail' item.pk %}">{{ item.name }}</a></li>
    {% endfor %}
</ul>


{% endblock %}

my_site/templates/index.html
{% extends "./base.html" %}

{% block content %}

Добро пожаловать в {{ title }}. <br>
Тут собрано {{ books|length }} книг из моей личной коллекции.

<table class="table table-bordered">
    <tr>
        <td scope="col">№</td>
        <td scope="col">Название</td>
        <td scope="col">ISBN</td>
        <td scope="col">Описание</td>
        <td scope="col">Год издания</td>
        <td scope="col">Автор</td>
        <td scope="col">Страна</td>
        <td scope="col">Кол-во копий</td>
    </tr>
    {% for book in books %}
    <tr>
        <td scope="row">{{ forloop.counter }}</td>
        <td ><a href="{% url 'p_library:book_detail' book.pk %}">{{ book.title }}</a></td>
        <td>{{ book.ISBN }}</td>
        <td>{{ book.description }}</td>
        <td>{{ book.year_release }}</td>
        <td>{{ book.author.full_name }}</td>
        <td>{{ book.author.country }}</td>
        <td>
            {{ book.copy_count }}               
            <form class="form-inline" action="/index/book_increment/" method="post" enctype="multipart/form-data">      
                    {% csrf_token %}
                    <input type="hidden" name="id" value="{{book.id}}" />
                    <button class="btn btn-outline-primary btn-sm" type="submit">+</button>
            </form>
            <form class="form-inline" action="/index/book_decrement/" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <input type="hidden" name="id" value="{{book.id}}" />
                    <button class="btn btn-outline-primary btn-sm" type="submit">-</button>
            </form>
        </td>
    </tr>
    {% endfor %}
</table>

<ul>
    {% for i in loop %}
        {% if i|divisibleby:"3" %}
        <li>
            {{ i }}
        </li>
        {% endif %}
    {% endfor %}
</ul>

{% endblock %}

my_site/templates/item_add.html
{% extends "./base.html" %}

{% block content %}

<form method="post">  
	{% csrf_token %}  
	{{ form.as_p }}  
	<input type="submit" class="btn btn-primary" value="Сохранить">  
</form>  

{% endblock %}

my_site/templates/publisher_detail.html
{% extends "./base.html" %}

{% block content %}

<div class="card w-100" style="width: 18rem;">
    <ul class="list-group list-group-flush">
        <li class="list-group-item">{{ object.name }}</li>
        <li class="list-group-item">Страна: {{ object.description }}</li>
    </ul>
    <div class="card-body">
    <a href="" class="card-link">Книги</a>
  </div>
</div>


{% endblock %}

my_site/templates/publishers.html
{% extends "./base.html" %}

{% block content %}
{% regroup publishers by publisher as publishers_list %}
<ul>
    {% for publisher in publishers_list %}
        <li>
            {% if publisher.grouper.name %}
                <a href="{% url 'p_library:publisher_detail' publisher.grouper.pk %}">{{ publisher.grouper.name }}</a>
            {% else %}
                Нет издателя
            {% endif %}
                <ul>
                    {% for item in publisher.list %}
                        <li> {{ item.title }}</li>
                    {% endfor %}
                </ul>
        </li>
    {% endfor %}
</ul>

{% endblock %}